### ISSUE TITLE
List tours

### ISSUE THREAD

**Issue by nguyendviet** [umgc/spring2023#11]
Build a Flutter page that can show all tours for `GET` request to the endpoint `/` or all current user's tours for `GET` request to the endpoint `/user/<user_id>/tours`.
The page should include the edit option on each tour for the endpoint `/user/<user_id>/tours` result.

## Note
This is a big task. Assignee(s) can break down this task into smaller tasks.

**Comment by tpbnick** [comment]
Working PR here - https://github.com/umgc/spring2023/pull/26

**Comment by tpbnick** [comment]
Merged into `team_a_dev` branch

**Comment by nguyendviet** [comment]
@tpbnick 
This is not really done so we should keep it open.
There will be changes when Team B finalises their returned JSON. 
If you want to keep this one as "Closed", please clone/create another ticket for yourself.

**Comment by nguyendviet** [comment]
@tpbnick Can you fix these issues?
- GET request gets connection refused error on Android. [Cause](https://github.com/umgc/spring2023/blob/team_a_dev/virotour/lib/src/tour/tour_list_view.dart#L34-L35)
<img width="587" alt="Screenshot 2023-03-08 at 23 39 54" src="https://user-images.githubusercontent.com/30057363/223918898-cdb051b7-d05b-415d-b284-d49f4f8cae03.png">
- The tours are left aligned on Chrome.
<img width="1209" alt="Screenshot 2023-03-08 at 23 39 02" src="https://user-images.githubusercontent.com/30057363/223918924-ce5a970b-889f-4bf4-8933-daf4ac68f26b.png">

**Comment by tpbnick** [comment]
Looking at this now

**Comment by nguyendviet** [comment]
Completed
