### ISSUE TITLE
Edit tour

### ISSUE THREAD

**Issue by nguyendviet** [umgc/spring2023#15]
- Build the functionality that allows users to edit a tour's information including all `informational hotspots` (add, edit, delete).
- Handle errors when editing.
- Send `POST` request to the endpoint `/<tour_id>` with a `tour_info` object
- Send `POST` request to the endpoint `/tour_id>` with a `blob_id`
- Send `POST` request to the endpoint `/tour_id>/<blob_id>`. This is similar to `PUT`.
- Send `DELETE` request to the endpoint `/tour_id>/<blob_id>`

**Comment by tpbnick** [comment]
This code was included in my list tours work.  It has been merged into `team_a_dev`.  The code will have to be updated once Team B's API endpoints allow uploading images.
