### ISSUE TITLE
Tour page

### ISSUE THREAD

**Issue by nguyendviet** [umgc/spring2023#19]
Create the page for a single tour. This page should:
- Display the 360 images correctly.
- Show smooth transition between each transitional hotspots / locations.
- Provide options to perform CRUD ops for informational hotspots if the current user is the creator of the tour.

**Comment by nguyendviet** [comment]
Nick's research:
Was looking into how we're going to actually add hotspots to the images and ChatGPT was actually pretty helpful.  It gave the following information: To add hotspots to a panoramic picture in Flutter, you can use a plugin such as panorama or panorama_view. Here are the general steps you can follow:Import the panorama or panorama_view plugin into your Flutter project.Load your panoramic image using the plugin.Add hotspots to the panoramic image using the GestureDetector widget. You can add InkWell or InkResponse widgets as children to the GestureDetector widget to detect the click events.When a user clicks on a hotspot, use the Navigator widget to navigate to another panoramic picture or page.Store the URLs of the next panoramic pictures in a database or JSON file (Team B is already working on this)Here's an example code snippet to add a hotspot using the panorama plugin: hotspot Dart
```dart
import 'package:flutter/material.dart';
import 'package:panorama/panorama.dart';
class MyPanorama extends StatelessWidget {
  @override  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Panorama(
          child: Stack(
            children: [
              // Your panoramic image              Image.network('https://example.com/my-panorama.jpg'),
              // Hotspot              Positioned(
                left: 100,
                top: 100,
                child: GestureDetector(
                  onTap: () {
                    // Navigate to another panoramic picture or page                    Navigator.pushNamed(context, '/another-panorama');
                  },
                  child: Container(
                    width: 50,
                    height: 50,
                    color: Colors.transparent,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
This example adds a hotspot at the position (100, 100) on the panoramic image. When the hotspot is clicked, it navigates to another panoramic picture or page. It would be pretty easy to also add popup boxes for certain types of hotspots (like informational) that show a box with text instead of taking you to another image.  Ivelin said that they are planning on storing hotspot information with X, Y coordinates, which would work perfectly with something like the above code.

**Comment by tpbnick** [comment]
Started working on it here:
https://github.com/umgc/spring2023/tree/interactive_tour_view
I have a basic movement between two images with hotspots working:
https://streamable.com/d6oghi

**Comment by tpbnick** [comment]
@nguyendviet I have the full tour hardcoded - https://github.com/umgc/spring2023/pull/61 please take a look and see if it is viable to build the required HTML for the WebViewX
